- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: go-interview   
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: go-interview
    template:
      metadata:
        labels:
          app: go-interview
      spec:
        nodeSelector:
          beta.kubernetes.io/os: linux
        containers:
          - name: go-interview
            image: gointerview.azurecr.io:latest
            env:
              - name: ALLOW_EMPTY_PASSWORD
                value: 'yes'
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 250m
                memory: 256Mi
            ports:
              - containerPort: 8080
                name: go-interview
- apiVersion: v1
  kind: Service
  metadata:
    name: go-interview
  spec:
    ports:
      - port: 8080
        # Port to forward to inside the pod
        targetPort: 8080
    selector:
      app: go-interview
 
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: test-ingress
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  spec:
    rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: go-interview
            servicePort: 8080
