apiVersion : apps/v1
kind: Deployment
metadata:
  name: go-interview
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-interview
  strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 0
         maxUnavailable: 1
  template:
    metadata:
      labels:
        app: go-interview      
    spec:
      containers:
        - name: go-interview 
          image: gointerview.azurecr.io:latest
          ports:
          - containerPort: 8080
