apiVersion : apps/v1
kind: Deployment
metadata:
  name: go-interview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-interview
  template:
    metadata:
      labels:
        app: go-interview 
    spec:
      containers:
        - name: go-interview 
          image: gointerview.azurecr.io:latest
          ports:
          - containerPort: 8080
