apiVersion : apps/v1
kind: Deployment
metadata:
  name: gointerviewapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  gointerviewapp
  template:
    metadata:
      labels:
        app: gointerviewapp     
    spec:
      containers:
        - name: gointerviewapp
          image: gointerviewhaidner.azurecr.io/go/gointerviewapp:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
