apiVersion : apps/v1
kind: Deployment
metadata:
  name: go-interview-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  go-interview-app
  template:
    metadata:
      labels:
        app: go-interview-app     
    spec:
      containers:
        - name: gointerviewapp
          image: gointerviewhaidner.azurecr.io/go/gointerviewapp:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
