apiVersion: v1
kind: Service
metadata:
    name: "bigcalfaks-8b39"
    labels:
        app: "bigcalfaks-8b39"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "bigcalfaks-8b39"